import js from "@eslint/js"
import globals from "globals"
import importPlugin from "eslint-plugin-import-x"
import prettier from "eslint-config-prettier"

export default [
  js.configs.recommended,
  {
    languageOptions: {
      globals: globals.browser,
    },
    plugins: { import: importPlugin },
    rules: {
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "import/order": ["error", { "newlines-between": "always" }],
    },
  },
  prettier,
  {
    ignores: [
      "node_modules/**",
      "public/assets/**",
      "public/packs/**",
      "coverage/**",
      "mobile/**",
      "app/javascript/controllers/index.js", // auto-generated by rails stimulus:manifest:update
    ],
  },
]
