---
:authors: Michael Milewski
:state: ✅ ACCEPTED
:Labels: ADR, process
---

= Architecture Decision Record template

== Context

As our product develops incrementally so does the Architecture of our code and
processes. Although all our code changes are tracked through version control,
this does not always capture the motivation behind certain decisions. As a
person joins an engineering team, they may be perplexed, baffled, delighted or
infuriated with some past decision. Without understanding the rational or
consequences of a particular decision, they can:

1. Blindly accept the decision
1. Blindly change it

The Architecture Decision Record, ADR, is a way to set the context at the time
of a decision, the approaches available and why they were chosen, what driving
factors lead to a particular decision.

inspired by

- https://www.cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]
- https://oxide.computer/blog/rfd-1-requests-for-discussion[RFD 1 Requests for Discussion / Oxide]

== Decision

We will keep a collection of records for “Architecturally significant” Decision:

- affect structure
- non-functional characteristics
- dependencies
- interfaces
- construction techniques
- company processes
- dependencies on 3rd parties (services or libraries)

An architecture decision record is a short text file. Each record describes a
set of forces and a single decision in response to those forces. Note that the
decision is the central piece here, so specific forces may appear in multiple
ADR's.

We will keep ADR's in GIT.

ADR's will be numbered sequentially and monotonically. Numbers will not be
reused.

If a decision is reversed, we will keep the old one around, but mark it as
superseded. (It's still relevant to know that it was the decision, but is no
longer the decision.)

We will use a format with just a few parts, so each document is easy to digest.
The format has just a few parts.

- **Title** These documents have names that are short noun phrases. For
  example, `adr/0001-architecture-decision-record-template`

- **Status** one of:
  - ⚠️ PROPOSED
  - ✅ ACCEPTED
  - ❌ REJECTED
  - DEPRECATED
  - SUPERSEDED

- **Context** This section describes the forces at play, including
  technological, political, social, and project local. These forces are
  probably in tension, and should be called out as such. The language in this
  section is value-neutral. It is simply describing facts.

- **Decision** This section describes our response to these forces. It is
  stated in full sentences, with active voice. "We will …"

- **Consequences** This section describes the resulting context, after applying
  the decision. All consequences should be listed here, not just the "positive"
  ones. A particular decision may have positive, negative, and neutral
  consequences, but all of them affect the team and project in the future.

- **Decision Log** a log of discussions, who was involved, other ideas and any
  warnings for our future selves, as a minimum, the decision log should include
  the **ADR review meeting**.

The whole document should be one or two pages long. We will write each ADR as
if it is a conversation with a future developer. This requires good writing
style, with full sentences organised into paragraphs. Bullets are acceptable
only for visual style, not as an excuse for writing sentence fragments.
(Bullets kill people, even PowerPoint bullets.)

== Consequences

One ADR describes one significant decision for a specific project. It should be
something that has an effect on how the rest of the project will run.

The consequences of one ADR are very likely to become the context for
subsequent ADR's.

Developers and project stakeholders can see the ADR's, even as the team
composition changes over time.

The motivation behind previous decisions is visible for everyone, present and
future. Nobody is left scratching their heads to understand, "What were they
thinking?" and the time to change old decisions will be clear from changes in
the project's context.

== Decision Log

**16 Jun 2026 - ADR formed**

- adr formulated and self approved by @saramic (Michael Milewski)
